### ISSUE TITLE
 Call to undefined method Terminus\Models\Environment::getHostnames()

### ISSUE THREAD

**Issue by dalin-** [pantheon-systems/all-aliases-plugin#2]
When running this plugin on Terminus 0.10.3
I get the error:

```
PHP Fatal error:  Call to undefined method Terminus\Models\Environment::getHostnames() in /home/vagrant/terminus/plugins/all-aliases/Commands/PantheonAliases.php on line 92
```

But when running on 0.10.2 it works fine without errors.

**Comment by jcowher** [comment]
I was having the same problem. I created a fork that fixes the issue. https://github.com/jcowher/all-aliases-plugin
