### ISSUE TITLE
Issues with Terminus 1.6

### ISSUE THREAD

**Issue by doostinharrell** [pantheon-systems/all-aliases-plugin#7]
I've installed this plugin as well as the latest version of terminus however I do not have access to the `sites aliases` command.  There were a few issues with the composer.json file which I resolved locally (missing type and extra definitions) as well.

Any ideas?

**Comment by doostinharrell** [comment]
Actually it looks like the command names have changed since the 1.x release of terminus.
https://pantheon.io/docs/terminus/get-started/legacy/

**Comment by greg-1-anderson** [comment]
This plugin currently only works with Terminus 0.x.  A version for Terminus 1.x will be available shortly.

**Comment by greg-1-anderson** [comment]
The 1.x branch of this plugin now works with Terminus 1.9 and later.
